import { Command, getPath, Dir, getPluginPath, JsonFormatter, openInBrowser } from "@maro/maro";
import { MdFile } from "../md_file";
import { NoteFile } from "../note_file";
import { createServer } from "vitepress";

const port = 3000
const ignores = [".gitignore", "node_modules"]

function buildNav(content: Dir) {
  const nav: any[] = [];
  if (content.hasFile("index.md")) nav.push({ text: "Home", link: "/" });

  for (const dir of content.readDirs()) {
    if (ignores.includes(dir.name())) continue;
    nav.push({ text: dir.name(), link: `/${dir.name()}/` });

    const files = dir.readFiles()
      .filter(f => !ignores.includes(f.name()))
      .map(f => ({
        file: f,
        note: new NoteFile(f.path)
      }))
      .sort((a, b) => {
        const da = new Date(a.note.read().metadata.date || 0).getTime()
        const db = new Date(b.note.read().metadata.date || 0).getTime()
        return db - da
      });

    const links = files.map(({ file, note }) => {
      const name = file.name({ extension: false })
      const title = note.read().metadata.title || name
      return `- [${title}](./${name})`
    }).join("\n")

    const index = new MdFile(dir.createFile("index.md").path)
    if (!index.exists()) index.write({
      title: dir.name(),
      subtitle: "Pages",
      content: links || "No pages in this section."
    });

  }
  return nav;
}

function buildSidebar(dir: Dir, base = ""): any[] {
  const items: any[] = [];

  for (const file of dir.readFiles()) {
    const name = file.name({ extension: false })
    if (ignores.includes(name)) continue
    if (name === "index" && base === "") continue;
    const note = new NoteFile(file.path)
    const title = note.read().metadata.title
    items.push({ text: title, link: `${base}/${name}`.replace(/^\/+/, "") });
  }

  for (const sub of dir.readDirs()) {
    if (ignores.includes(sub.name())) continue
    const children = buildSidebar(sub, `${base}/${sub.name()}`);
    if (children.length === 0) continue;
    items.push({ text: sub.name(), items: children });
  }

  return items;
}

export const WebCommand: Command = {
  name: "web",
  run: async () => {
    const notes = getPath("notes");
    const plugin_path = new Dir(getPluginPath())
    const content_dir = plugin_path.sub("content")

    if (content_dir.exists()) content_dir.delete()
    notes.copy(content_dir)

    const index = new MdFile(content_dir.createFile("index.md").path)
    if (!index.exists()) index.write({
        title: "Welcome to notes",
        content: "This page is autogenerated by maro-plugin-notes"
      })

    const vitepress = plugin_path.sub(".vitepress")
    if (vitepress.exists()) vitepress.delete()
    vitepress.create()
    const config_file = vitepress.createFile("config.ts")

    const sidebar = buildSidebar(content_dir)
    const navbar = buildNav(content_dir)
    const formatter = new JsonFormatter()
    config_file.write(`
export default {
  srcDir: 'content',
  title: 'Notes',
  themeConfig: {
  search: {
    provider: 'local'
  },
    nav: ${formatter.toString(navbar)},
    sidebar:${formatter.toString(sidebar)}
  }
}
`)

    const server = await createServer(plugin_path.path)
    await server.listen(port)
    console.log(`Server listening on port ${port}...`)
    openInBrowser(`http://localhost:${port}`)
  }
}
